---
title: "intro"
format: html
---

## Substance Use Disorders
In 2023, over 46 million U.S. adults had a substance use disorder (SUD) in the past year [@substanceabuseandmentalhealthservicesadministration2023NSDUHDetailed]. Substance use disorders are associated with high rates of morbidity and mortality. Opioid overdose rates remain high and continue to increase each year [@IncreasesDrugOpioid; @friedmanTrendsDrugOverdose2022]. Excessive alcohol use is a leading preventable cause of death, with the majority of these deaths caused by alcohol-attributed cancer, heart problems and stroke, and liver cirrhosis [@ARDIAlcoholAttributableDeaths]. Additionally, alcohol-impaired driving accounts for over 30% of traffic fatalities each year [@unitedstatesdepartmentoftransportation2024].  

The economic cost of substance use disorders is substantial. In 2016 the economic cost associated with substance use disorders was estimated to exceed \$442 billion in lost productivity, health care expenses, law enforcement, and other criminal justice costs [@substanceabuseandmentalhealthservicesadministrationusFacingAddictionAmerica2016]. When also accounting for costs associated with loss of life and reduced quality of life, one research group estimated that in 2017 the cost of opioid use disorder alone exceeded \$1 trillion [@florenceEconomicBurdenOpioid2021]. 

SUDs are chronic, relapsing conditions [@mclellanDrugDependenceChronic2000; @mckayImpactContinuingCare2021]. Effective pharmacological and psychosocial interventions exist to support symptom stabilization and reduce substance use [@bowenMindfulnessBasedRelapsePrevention2021; @marlattRelapsePreventionSecond2007; @lieseCognitiveBehavioralTherapyAddictive2022]. Despite the availability of effective treatments, the majority of individuals with SUDs do not receive care. In 2023, less than 15% of individuals with an SUD received any form of treatment, a stark comparison to treatment initiation for other chronic diseases [@substanceabuseandmentalhealthservicesadministration2023NSDUHDetailed. Even among the minority who do initiate treatment, engagement is often brief and episodic. Relapse back to substance use is common, particularly in the absence of continued treatment engagement and recovery support. Importantly, relapse rates for SUDs are comparable to recurrence rates in other chronic conditions (e.g., type I diabetes, hypertension, asthma) when medication adherence and follow-up care are inconsistent. Thus, the recurrence of symptoms is not unique to SUDs but rather a challenge inherent in chronic disease management without adequate continuing care.

These patterns reflect structural limitations within the current treatment system. Several factors, including cost and insurance reimbursement issues, lack of collaborative provider teams, passive referral processes, geographic barriers to accessing services, patient dropout, and changes in the patient’s clinical needs over time, suggest our current treatment system for SUDs does not have the capacity for long-term clinician-delivered care [@dennisManagingAddictionChronic2007; @taiTreatmentSubstanceUse2013; @mckayImpactContinuingCare2021; @stanojlovicTargetingBarriersSubstance2021]. Stigma surrounding SUD and historical views of substance use as a social or behavioral problem have contributed to the siloing of SUD care. Treatment typically occurs in specialized, community-based settings that are disconnected from primary care. This fragmented infrastructure results in poor care coordination, missed opportunities for early intervention and re-engagement, and a "revolving door" pattern in which individuals cycle repeatedly through acute episodes of care as opposed to receiving long-term chronic disease management.


## Disparities in SUD Treatment Access and Outcomes
Limitations of the current SUD treatment infrastructure are magnified for people with certain identities. Women, low income individuals, rural residents, and older adults may face unique barriers to treatment, including financial constraints, limited service availability, and mobility or transportation challenges. Marginalized groups, such as racial, ethnic, and sexual minorities additionally may additionally experience minority stress, stigma, discrimination, and isolation leading to higher rates of SUD and poorer treatment outcomes. 

Black and Hispanic individuals are less likely to receive treatment and are more likely to experience negative consequences associated with SUDs [@pinedoCurrentReexaminationRacial2019; @guerreroDisparitiesLatinoSubstance2013; @schmidtEthnicDisparitiesClinical2007; @kilaruIncidenceTreatmentOpioid2020]. Among those who do receive treatment, dropout rates are higher compared to non-Hispanic White individuals [@salonerBlacksHispanicsAre2013]. Hispanic and non-White individuals are also more likely to face socioeconomic barriers, including unemployment and housing instability. 

Sexual minority populations experience disproportionately high rates of SUD compared to heterosexual populations [@freitagVariationsSubstanceUse2021; @craneAlcoholUseDisorders2020]. Some research suggests that these elevated rates are related to depleted coping mechanisms resulting from chronic minority stress and enacted stigma (e.g., discrimination, biased treatment, microaggressions) [@dyarSexualMinorityStress2023; @kruegerSexualOrientationDisparities2020]. These disparities intensify when sexual orientation intersects with other identities such as race or gender [@freitagVariationsSubstanceUse2021; @kerridgePrevalenceSociodemographicCorrelates2017].

Women are less likely than men to enter treatment [@greenfieldSubstanceAbuseTreatment2007; @kilaruIncidenceTreatmentOpioid2020] and more frequently experience barriers related to unemployment, financial dependence, psychiatric comorbidities, and childcare responsibilities. Women who are pregnant or have children often report avoiding treatment because they fear losing custody or having their baby removed [@greenfieldSubstanceAbuseTreatment2007; @parlier-ahmadExploratoryStudySex2021]. Women are also more vulnerable to adverse health and social consequences of SUDs [@mchughSexGenderDifferences2018]. They typically show an accelerated progression from onset of use to treatment entry and develop severe symptoms over fewer years compared to men [@campbellBriefReportGender2018].  

Low-income individuals face heightened risk for developing SUD and greater challenges accessing treatment. Prior to the 2014 Affordable Care Act, financial barriers prevented many low-income individuals from accessing SUD treatment. The Affordable Care Act expanded Medicaid eligibility to include nearly all low-income individuals, broadening access to government-funded SUD treatment services. This expansion has also been shown to reduce racial and ethnic disparities in access to care, as minorities are disproportionately represented among low-income populations [@lecookRacialEthnicDisparitiesSubstance2011]. Nevertheless, low income remains associated with higher rates of SUD, more severe SUD, and co-occurence with socioenvironmental risk factors that can interfere with treatment and recovery [@grantEpidemiologyDSM5Alcohol2015b].

Rural areas have higher SUD prevalence yet fewer treatment clinics and providers [@listerSystematicReviewRuralspecific2020]. This imbalance results in a disproportionate SUD burden for rural residents, including elevated opioid overdose rates and treatment waitlists that may last months to years [@sigmonAccessTreatmentOpioid2014]. For individuals who do get treatment, services are often not near by. The time and financial costs associated with travel contribute to missed appointments and early treatment dropout. This is especially true for individuals receiving medication for OUD, who often must attend daily clinic visits for observed dosing. Stigma surrounding SUD treatment may also be higher in small rural communities where services are more visible and harder to access discreetly [@woodLotPeopleCall2019].

Older adults (65+) are less likely to receive SUD treatment or perceive a need for treatment compared to younger age groups [@choiTreatmentUsePerceived2014; @kilaruIncidenceTreatmentOpioid2020]. They are also more likely to experience complicating factors such as medical comorbidities, chronic pain and heightened sensitivity to medication interactions and side effects [@kuerbisSubstanceAbuseOlder2014; Salive]. Additionally, factors such as being divorced or widowed, retired, or having fewer social activities may reduce opportunities for family or friends to notice harmful substance use. Doctors and clinicians may also attribute SUD symptoms to other health or age-related issues.


## Relapse Prevention
Recovery from substance use disorders is a non-linear and dynamic process [@witkiewitzRelapsePreventionAlcohol2004]. Lapses back to substance use are common and, on their own, do not necessarily constitute relapse (i.e., a full return to problematic use). Nevertheless, lapses must precede relapse and therefore can be viewed as early warning signs, making them clinically meaningful targets for intervention and prevention.   

An extant relapse prevention literature has identified a range of intrapersonal precursors to lapse and relapse. These include self‑efficacy (i.e., confidence in one's ability to maintain abstinence), craving, motivation, emotional states, and coping‑related or substance‑use behaviors [@witkiewitzRelapsePreventionAlcohol2004; @witkiewitzTherapistsGuideEvidenceBased2007; @marlattRelapsePreventionSecond2007]. These risk factors differ across individuals and within an individual over time. They interact with one another and with interpersonal and environmental situations to influence lapse risk [@stantonRelapsePreventionNeeds2005; @witkiewitzRelapsePreventionAlcohol2004]. For example, cravings are typically short-lived urges. Individuals in recovery-supportive environments may be able to ride out these cravings successfully. However, in unsupportive environments (e.g., locations with easily available alcohol or exposure to other substance-related cues), the likelihood of lapse increases. Given the complex, interactive, and time-varying nature of lapse risk, self-monitoring is difficult.

## Recovery Monitoring and Support System
An algorithm-guided recovery monitoring and support system could help individuals monitor their current and future risk of lapse and make adjustments in their activities and supports to meet their recovery goals after initial treatment. Such a tool could offer personalized, adaptive recommendations aligned with evidenced-based care and prompt individuals to engage with support at times of high risk. For example, individuals could receive daily messages about changes in their lapse risk and receive personalized recommendations based on top features contributing to their risk. Moreover, it would provide a scalable option for long-term monitoring and support to address the substantial unmet need for continuing care for SUDs. 

For such a system to exist, at least three pre-requisites must be met. One, the system must be able to collect a rich and densely sampled source (or sources) of risk-relevant data. Two, the system must have access to a model that can predict substance use with high performance and temporal precision and have interpretable model inputs for support recommendations to be mapped onto. Three, the model must perform fairly. The accuracy of the predictions and usefulness and relevance of the recommendations should be similar for everyone. Advances in both smartphone sensing [@mohrPersonalSensingUnderstanding2017] and machine learning [@hastieElementsStatisticalLearning2009] now make this possible.

Smartphone sensing approaches (e.g., ecological momentary assessment [EMA], geolocation sensing) can provide the frequent, longitudinal measurement of proximal risk factors that is necessary for prediction of future lapses with high temporal precision. Individuals with substance use disorders have demonstrated a willingness to provide EMA over extended periods of time with adequate adherence [@jonesComplianceEcologicalMomentary2019; @alexanderUseEcologicalMomentary2023; @wyantAcceptabilityPersonalSensing2023]. Individuals with alcohol use disorder who provided geolocation data for up to three months reported generally finding this sensing method acceptable and being willing to provide the data for up to a year [@wyantAcceptabilityPersonalSensing2023]. Moreover, the proliferation of smartphone usage in recent years makes smartphone sensing a potentially scalable and equitable method for improving lapse risk monitoring. As of 2025, roughly 91% of Americans own a smartphone and smartphone ownership is consistently high (>= 85%) across gender, race and ethnicity, socioeconomic status, and geographic location [@DemographicsMobileDevice2025]. 

Machine learning models can handle the high dimensional feature sets that may result from feature engineering densely sampled sensing data over time. They can also accommodate non-linear and interactive relationships between features and lapse probability.  And methods from interpretable machine learning can be used to understand which risk features contribute most strongly to a lapse prediction for a specific individual at a specific moment in time. Studies have begun to demonstrate how sensing features can be used to predict substance use with high accuracy [@baeMobilePhoneSensors2018; @waltersUsingMachineLearning2021; @baeLeveragingMobilePhone2023; @soysterPooledPersonspecificMachine2022; @heinzLongitudinalObservationalStudy2025]. While these studies are promising, they are limited in their generalizability to a recovery monitoring and support system. First, the majority of these studies pedict substance use episodes in non-treatment seeking populations [@baeMobilePhoneSensors2018; @baeLeveragingMobilePhone2023; @waltersUsingMachineLearning2021; @soysterPooledPersonspecificMachine2022]. The precursors to goal-inconsistent substance use (i.e., lapses) in populations with substance use disorder may vastly differ from planned or intentional substance use episodes. Second, none of these studies explicitly assessed the fairness of the machine learning models. An automated recovery monitoring and support system offers opportunity for mitigating many of the accessibility, affordability, and stigma barriers that contribute to treatment disparities. However, a model that performs poorly in certain groups may exacerbate these disparities [@timmonsCallActionAssessing2023]. 


## Specific Aims
This dissertation presents a series of studies aimed to address the current limitations in the lapse prediction literature. Specifically, we designed three studies to develop fair and temporally precise machine learning models for lapse risk prediction back to alcohol and opioid use that could be used in a recovery monitoring support system. 

To meet this goal, we used two clinical samples of participants in early recovery from alcohol and opioid use disorder.  

- 2 clinical samples 
- fairness evaluation
- model interpretability and mapping to recommendations




