---
title: "Make All Tables for Dissertation"
author: "Kendra Wyant"
date: "`r lubridate::today()`"
number-sections: true
output: 
  html_document:
    toc: true 
    toc_depth: 4
format:
  html:
    embed-resources: true
    toc: true
    toc-depth: 4
editor_options: 
  chunk_output_type: console
html-table-processing: none
---

```{r}
#| message: false
#| warning: false

suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(source("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true"))
suppressPackageStartupMessages(library(tidyposterior))
library(kableExtra)

path_models_lag <- format_path(str_c("risk/models/lag"))
path_shared <- format_path("risk/data_processed/shared")
path_processed_lag <- format_path("risk/data_processed/lag")
path_models_ema<- format_path(str_c("risk/models/ema"))
path_processed_ema <- format_path("risk/data_processed/ema")
path_risk2 <- "S:/risk2/data_processed/shared"
path_models_risk2 <- "S:/risk2/models/combined"




options(knitr.kable.NA = '')
```


# Chapter 2: EMA 

## Data and calculations


```{r}
disposition <- read_csv(file.path(path_processed_ema, "disposition.csv"), 
                        col_types = "ccDDcccccccccc")

screen <- read_csv(file.path(path_shared, "screen.csv"), 
                   col_types = cols()) |>
  filter(subid %in% subset(disposition, analysis == "yes")$subid) |> 
  mutate(across(dsm5_1:dsm5_11, ~ recode(., "No" = 0, "Yes" = 1))) |>  
  rowwise() |>  
  mutate(dsm5_total = sum(c(dsm5_1, dsm5_2, dsm5_3, dsm5_4, dsm5_5, dsm5_6, dsm5_7, 
                              dsm5_8, dsm5_9, dsm5_10, dsm5_11))) |>  
  ungroup()

lapses <- read_csv(file.path(path_shared, "lapses.csv"), col_types = cols()) |>
  filter(exclude == FALSE)

# Calcs to make df for table 1 (demographics and clinical characteristics)
n_total <- 151

dem_age <- screen |>
  summarise(mean = as.character(round(mean(dem_1, na.rm = TRUE), 1)),
            SD = as.character(round(sd(dem_1, na.rm = TRUE), 1)),
            min = as.character(min(dem_1, na.rm = TRUE)),
            max = as.character(max(dem_1, na.rm = TRUE))) |>
  mutate(var = "Age",
         n = as.numeric(""),
         perc = as.numeric("")) |>
  select(var, n, perc, everything()) 

dem_sex <-  screen |>
  select(var = dem_2) |>
  group_by(var) |>
  summarise(n = n()) |>
  mutate(perc = (n / sum(n)) * 100) |> 
  add_row(var = "Sex", .before = 1)

dem_race <- screen |>
  select(var = dem_3) |>
  mutate(var = fct_relevel(factor(var,
                         c("American Indian/Alaska Native", "Asian", "Black/African American",
                           "White/Caucasian", "Other/Multiracial")))) |>
  group_by(var) |>
  summarise(n = n()) |>
  mutate(perc = (n / sum(n)) * 100) |>
  add_row(var = "Race", .before = 1)
  
  
dem_ethnicity <- screen |>
  select(var = dem_4) |>
  mutate(var = case_when(var == "No, I am not of Hispanic, Latino, or Spanish origin" ~ "No",
                         TRUE ~ "Yes"),
         var = fct_relevel(factor(var, c("Yes", "No")))) |>
  group_by(var) |>
  summarise(n = n()) |>
  mutate(perc = (n / sum(n)) * 100) |>
  add_row(var = "Hispanic, Latino, or Spanish origin", .before = 1)

dem_education <- screen |>
  select(var = dem_5) |>
  mutate(var = fct_relevel(factor(var,
                         c("Less than high school or GED degree", "High school or GED",
                           "Some college", "2-Year degree", "College degree", "Advanced degree")))) |>
  group_by(var) |>
  summarise(n = n()) |>
  mutate(perc = (n / sum(n)) * 100) |>
  add_row(var = "Education", .before = 1)

dem_employment <- screen |>
  select(var = dem_6, dem_6_1) |>
  mutate(var = case_when(dem_6_1 == "Full-time" ~ "Employed full-time",
                         dem_6_1 == "Part-time" ~ "Employed part-time",
                         TRUE ~ var)) |>
  mutate(var = fct_relevel(factor(var,
                         c("Employed full-time", "Employed part-time", "Full-time student",
                           "Homemaker", "Disabled", "Retired", "Unemployed",
                           "Temporarily laid off, sick leave, or maternity leave",
                           "Other, not otherwise specified")))) |>
  group_by(var) |>
  summarise(n = n()) |>
  mutate(perc = (n / sum(n)) * 100) |>
  add_row(var = "Employment", .before = 1)

dem_income <- screen |>
  summarise(mean = format(round(mean(dem_7, na.rm = TRUE), 0), big.mark = ","),
            SD = format(round(sd(dem_7, na.rm = TRUE), 0), big.mark = ","),
            min =format(round(min(dem_7, na.rm = TRUE), 0), big.mark = ","),
            max = format(round(max(dem_7, na.rm = TRUE), 0), scientific = FALSE, big.mark = ",")) |>
  mutate(var = "Personal Income",
        n = as.numeric(""),
        perc = as.numeric(""),
        mean = str_c("$", as.character(mean)),
        SD = str_c("$", as.character(SD)),
        min = str_c("$", as.character(min)),
        max = as.character(max)) |>
  select(var, n, perc, everything())

dem_marital <- screen |>
  select(var = dem_8) |>
  mutate(var = case_when(var == "Never Married" ~ "Never married",
                         TRUE ~ var)) |>
  mutate(var = fct_relevel(factor(var,
                         c("Never married", "Married", "Divorced", "Separated",
                           "Widowed")))) |>
  group_by(var) |>
  summarise(n = n()) |>
  mutate(perc = (n / sum(n)) * 100) |> 
  add_row(var = "Marital Status", .before = 1)

dem_aud <- screen |>
  summarise(mean = as.character(round(mean(dsm5_total, na.rm = TRUE), 1)),
            SD = as.character(round(sd(dsm5_total, na.rm = TRUE), 1)),
            min = as.character(min(dsm5_total, na.rm = TRUE)),
            max = as.character(max(dsm5_total, na.rm = TRUE))) |>
  mutate(var = "DSM-5 AUD Symptom Count",
         n = as.numeric(""),
         perc = as.numeric("")) |>
  select(var, n, perc, everything()) 

lapses_per_subid <- screen |>
  select(subid) |>
  left_join(lapses |>
  janitor::tabyl(subid) |>
  select(-percent), by = "subid") |>
  mutate(n = if_else(is.na(n), 0, n),
         lapse = if_else(n > 0, "yes", "no"))

lapse_info <- lapses_per_subid |>
  group_by(lapse) |>
  rename(var = lapse) |>
  mutate(var = factor(var, levels = c("yes", "no"), labels = c("Yes", "No"))) |>
  summarise(n = n()) |>
  mutate(perc = (n / n_total) * 100,
         mean = NA_character_,
         SD = NA_character_,
         min = NA_character_,
         max = NA_character_) |>
  full_join(lapses_per_subid |>
  summarise(mean = as.character(round(mean(n), 1)),
            SD = as.character(round(sd(n), 1)),
            min = as.character(round(min(n), 1)),
            max = as.character(round(max(n), 1))) |>
  mutate(var = "Number of reported lapses"),
  by = c("var", "mean", "SD", "min", "max")) |> 
  add_row(var = "Reported 1 or More Lapse During Study Period", .before = 1)

table_dem <- dem_age |> 
  bind_rows(dem_sex) |> 
  bind_rows(dem_race) |> 
  bind_rows(dem_ethnicity) |> 
  bind_rows(dem_education) |> 
  bind_rows(dem_employment) |> 
  bind_rows(dem_income) |> 
  bind_rows(dem_marital) |> 
  bind_rows(dem_aud) |> 
  bind_rows(lapse_info) |> 
  mutate(range = str_c(min, "-", max),
         perc = round(perc, 1)) |> 
  select(-c(min, max)) |> 
  rename(N = n,
         `%` = perc,
         M = mean, 
         Range = range)
```

```{r}
# metrics
metrics_week <- read_csv(file.path(path_models_ema, "test_metrics_1week_0_v5_nested.csv"),
                         show_col_types = FALSE)
metrics_day <- read_csv(file.path(path_models_ema, "test_metrics_1day_0_v5_nested.csv"),
                        show_col_types = FALSE)
metrics_hour <- read_csv(file.path(path_models_ema, "test_metrics_1hour_0_v5_nested.csv"),
                         show_col_types = FALSE)

metrics <- metrics_week |> 
  mutate(model = "Week") |> 
  bind_rows(metrics_day |> 
              mutate(model = "Day")) |> 
  bind_rows(metrics_hour |> 
              mutate(model = "Hour")) |> 
  group_by(.metric, model) |> 
  summarize(median = median(.estimate), .groups = "drop") |> 
  pivot_wider(names_from = model, values_from = median) |> 
  select(.metric, Week, Day, Hour)

metrics <- metrics[c(4,5,6, 1, 3, 2),]

table_perf <- metrics |> 
 mutate(.metric = case_when(.metric == "roc_auc" ~ "auROC",
                            .metric == "sens" ~ "sensitivity",
                            .metric == "spec" ~ "specificity",
                            .metric == "bal_accuracy" ~ "balanced accuracy",
                            .metric == "ppv" ~ "positive predictive value",
                            .metric == "npv" ~ "negative predictive value")) |> 
 rename(Metric = .metric)
```





### Table 1: Demographic and Lapse Characteristics


```{r}
#| label: tbl-dem
#| tbl-cap: "Demographic and Lapse Characteristics"

table_dem |> 
  knitr::kable()

```


### Table 2: Performance Metrics

```{r}
#| label: tbl-perf-ema
#| tbl-cap: "Performance Metrics for Full models by Prediction Window"
#| tbl-footnote: "Areas under the receiver operating characteristic curves (auROCs) summarize the model's sensitivity and specificity over all possible decision thresholds. Sensitivity, specificity, balanced accuracy, positive predictive value, and negative predictive value are performance metrics calculated at a single decision threshold for each model determined with Youden’s index. All metrics represent median values across 30 held-out test sets."

table_perf |> 
  knitr::kable()

```



# Chapter 3: Lag

Table 1
```{r}
ci_baseline <- read_csv(here::here(path_models_lag, "contrast_baseline.csv"), 
                        col_types = cols())

ci_lag <- read_csv(here::here(path_models_lag, "contrast_adjacent.csv"), 
                   col_types = cols())
ci_fairness_0 <- read_csv(here::here(path_models_lag, "pp_dem_contrast_all.csv"), 
                   col_types = cols()) |> 
  filter(lag == 0)

ci_fairness_336 <- read_csv(here::here(path_models_lag, "pp_dem_contrast_all.csv"), 
                   col_types = cols()) |> 
  filter(lag == 336)

table_ci <- ci_baseline |> 
  mutate(ci = str_c("[", round(lower, 3), ", ", round(upper, 3), "]"),
         median = as.character(round(median, 3)),
         probability = as.character(round(probability, 3))) |> 
  select(contrast, median, ci, probability) |> 
  add_row(contrast = "Baseline Contrasts", median = "", ci = "", probability = "") |> 
  mutate(contrast = factor(contrast,
                           levels = c("Baseline Contrasts",
                                      "0 vs. 24",
                                      "0 vs. 72",
                                      "0 vs. 168",
                                      "0 vs. 336"),
                           labels = c("Baseline Contrasts",
                                      "No lag vs. 1 day",
                                      "No lag vs. 3 days",
                                      "No lag vs. 1 week",
                                      "No lag vs. 2 weeks"))) |> 
  arrange(contrast) |> 
  rbind(ci_lag |> 
          mutate(ci = str_c("[", round(lower, 3), ", ", round(upper, 3), "]"),
                  median = as.character(round(median, 3)),
         probability = as.character(round(probability, 3))) |>
          select(contrast, median, ci, probability) |> 
          add_row(contrast = "Adjacent Contrasts", median = "", ci = "", 
                  probability = "") |> 
          mutate(contrast = factor(contrast,
                           levels = c("Adjacent Contrasts",
                                      "24 vs. 72",
                                      "72 vs. 168",
                                      "168 vs. 336"),
                           labels = c("Adjacent Contrasts",
                                      "1 day vs. 3 days",
                                      "3 days vs. 1 week",
                                      "1 week vs. 2 weeks"))) |> 
          arrange(contrast)) |> 
    rename(Contrast = contrast,
         Median = median,
         `Bayesian CI` = ci,
         Probability = probability)
 
  table_ci_fair <- ci_fairness_0 |> 
          mutate(ci = str_c("[", round(lower, 3), ", ", round(upper, 3), "]"),
                  median = as.character(round(median, 3)),
         probability = as.character(round(probability, 3))) |>
          select(contrast, median, ci, probability) |> 
          add_row(contrast = "Fairness Contrasts (No Lag)", median = "", ci = "", 
                  probability = "") |> 
          mutate(contrast = factor(contrast,
                           levels = c("Fairness Contrasts (No Lag)",
                                      "male vs female",
                                      "non-hispanic white vs not white",
                                      "above poverty vs below poverty"),
                           labels = c("Fairness Contrasts (No Lag)",
                                      "male vs. female",
                                      "non-Hispanic White vs. not White",
                                      "above poverty vs. below poverty"))) |> 
          arrange(contrast) |> 
    rbind(ci_fairness_336 |> 
          mutate(ci = str_c("[", round(lower, 3), ", ", round(upper, 3), "]"),
                  median = as.character(round(median, 3)),
         probability = as.character(round(probability, 3))) |>
          select(contrast, median, ci, probability) |> 
          add_row(contrast = "Fairness Contrasts (2-week Lag)", median = "", ci = "", 
                  probability = "") |> 
          mutate(contrast = factor(contrast,
                           levels = c("Fairness Contrasts (2-week Lag)",
                                      "male vs female",
                                      "non-hispanic white vs not white",
                                      "above poverty vs below poverty"),
                           labels = c("Fairness Contrasts (2-week Lag)",
                                      "male vs. female",
                                      "non-Hispanic White vs. not White",
                                      "above poverty vs. below poverty"))) |> 
          arrange(contrast)) |> 
  rename(Contrast = contrast,
         Median = median,
         `Bayesian CI` = ci,
         Probability = probability)
```



### Table 2: Model Comparisons

```{r }
#| label: tbl-model
#| tbl-cap: "Median difference in auROC, 95% Bayesian credible interval (CI), and posterior probability that that the auROC difference was smaller than 0 for all baseline and adjacent lag contrasts."

footnote_table_model <- "Median auROC differences less than 0 indicate the more lagged model, on average, performed worse than the more immediate model (e.g., 1-day lag - no lag, 3-day lag - 1-day lag). Bayesian CI represents the range of values where there is a 95% probability that the true auROC difference lies within that range. Probability indicates the posterior probability that this difference is smaller than 0 (i.e., the models are performing differently)."

table_ci |> 
  knitr::kable() |> 
  kable_classic() |> 
  kableExtra::column_spec(1, width = "25em") |> 
  kableExtra::group_rows(start_row = 2, end_row = 5) |> 
  kableExtra::group_rows(start_row = 7, end_row = 9) |> 
  kableExtra::row_spec(5, extra_css = "border-bottom: 1px solid") |> 
  kableExtra::add_footnote(label = footnote_table_model,
                           notation = "none",
                           escape = FALSE)
```

### Table 3: Fairness Comparisons

```{r }
#| label: tbl-fairness
#| tbl-cap: "Median difference in auROC, 95% Bayesian credible interval (CI), and posterior probability that that the auROC difference was smaller than 0 for fairness contrasts for the no lag and 2-week lagged models."

footnote_table_fair <- "Median auROC differences less than 0 indicate the model, on average, performed worse for the disadvantaged group (female, non-White and/or Hispanic, income below poverty line) compared to the advantaged group (male, non-Hispanic White, income above poverty line). Bayesian CI represents the range of values where there is a 95% probability that the true auROC difference lies within that range. Probability indicates the posterior probability that this difference is smaller than 0 (i.e., the models are performing differently for fairness subgroups)."

table_ci_fair |> 
  knitr::kable() |> 
  kable_classic() |> 
  kableExtra::column_spec(1, width = "25em") |> 
  kableExtra::group_rows(start_row = 2, end_row = 4) |> 
  kableExtra::group_rows(start_row = 6, end_row = 8) |> 
  kableExtra::row_spec(4, extra_css = "border-bottom: 1px solid")  |> 
  kableExtra::add_footnote(label = footnote_table_fair,
                           notation = "none",
                           escape = FALSE)
```

## Chapter 4

Demographics
```{r}
study_dates <- read_csv(file.path(path_risk2, "study_dates_gps.csv"), 
                        show_col_types = FALSE)

location <- read_csv(file.path(path_risk2, "features_fairness.csv"), 
                        show_col_types = FALSE) |>
  filter(subid %in% study_dates$subid) 

intake <- read_csv(file.path(path_risk2, "survey_intake.csv"), 
                   show_col_types = FALSE) |>
  filter(subid %in% study_dates$subid) 


# Calcs to make df for table 1 (demographics and clinical characteristics)
n_total <- nrow(study_dates)

dem_age <-  intake |>
  select(var = age) |>
  group_by(var) |>
  summarise(n = n()) |>
  mutate(perc = (n / n_total) * 100) |> 
  add_row(var = "Age", .before = 1)

dem_gender <-  intake |>
  select(var = gender) |>
  filter(var != "Prefer not to say") |> 
  mutate(var = factor(var, 
                      levels = c("Man",
                                 "Woman",
                                 "Non-binary",
                                 "Not listed above"))) |> 
  group_by(var) |>
  summarise(n = n()) |>
  mutate(perc = (n / n_total) * 100) |> 
  add_row(var = "Gender", .before = 1)

dem_orientation <-  intake |>
  select(var = orientation) |>
  filter(!is.na(var)) |> 
  mutate(var = factor(var, levels = c("Straight, that is, not gay or lesbian",
                                      "Lesbian or gay",
                                      "Bisexual",
                                      "Not sure",
                                      "Not listed above"))) |> 
  group_by(var) |>
  summarise(n = n()) |>
  mutate(perc = (n / n_total) * 100) |> 
  add_row(var = "Orientation", .before = 1)

dem_race <- intake |>
  select(starts_with("race_"), -race_other_text) |> 
  pivot_longer(1:7, names_to = "var") |> 
  mutate(var = case_match(var,
                           "race_ai_an" ~ "American Indian/Alaskan Native",
                           "race_asian" ~ "Asian",
                           "race_black" ~ "Black/African American",
                           "race_nat_hi" ~ "Native Hawaiian/Other Pacific Islander",
                           "race_white" ~ "White/Caucasian",
                           "race_hispanic" ~ "Hispanic, Latino, or Spanish origin",
                           "race_other" ~ "Not listed above"),
         var = factor(var,levels = c("American Indian/Alaskan Native",
                                     "Asian",
                                     "Black/African American",
                                     "Native Hawaiian/Other Pacific Islander",
                                     "White/Caucasian",
                                     "Hispanic, Latino, or Spanish origin",
                                     "Not listed above"))) |> 
  group_by(var) |>
  count(value) |> 
  ungroup() |> 
  filter(value == "yes") |> 
  select(-value) |> 
  mutate(perc = (n / n_total) * 100) |>
  add_row(var = "Race and Ethnicity (select all that apply)", .before = 1)

dem_geography <- location |> 
  mutate(geography = if_else(geography == "urban/suburban", "urban", "rural")) |> 
  select(var = geography) |>
  group_by(var) |>
  summarise(n = n()) |>
  mutate(perc = (n / n_total) * 100) |> 
  add_row(var = "Geographic Location", .before = 1)
  

dem_education <- intake |>
  select(var = education) |>
  filter(!is.na(var)) |> 
  mutate(var = factor(var, 
                      levels = c("8th grade or less",
                                 "Some high school, but did not graduate",
                                 "High school graduate or GED",
                                 "Some college or 2-year degree",
                                 "4-year college graduate",
                                 "More than 4-year or advanced degree"))) |> 
  group_by(var) |>
  summarise(n = n()) |>
  mutate(perc = (n / n_total) * 100) |>
  add_row(var = "Education", .before = 1)

dem_employment <- intake |>
  select(var = employment) |>
  filter(!is.na(var)) |> 
  group_by(var) |>
  summarise(n = n()) |>
  mutate(perc = (n / n_total) * 100) |>
  add_row(var = "Employment", .before = 1)

dem_income <- intake |>
  select(var = income) |>
  filter(!is.na(var)) |> 
  mutate(var = factor(var, 
                      levels = c("Less than $25,000",
                                 "$25,000 - $34, 999",
                                 "$35,000 - $49,999",
                                 "$50,000 - $74, 999",
                                 "$75, 000 - $99, 999",
                                 "$100,000 - $149,999",
                                 "$150, 000 - $199,999",
                                 "$200, 000 or more"),
                      labels = c("Less than $25,000",
                                 "$25,000 - $34,999",
                                 "$35,000 - $49,999",
                                 "$50,000 - $74,999",
                                 "$75,000 - $99,999",
                                 "$100,000 - $149,999",
                                 "$150,000 - $199,999",
                                 "$200,000 or more"))) |> 
  group_by(var) |>
  summarise(n = n()) |>
  mutate(perc = (n / n_total) * 100) |>
  add_row(var = "Household Income", .before = 1)


dsm <- intake |>
  summarise(mean = mean(dsm_c, na.rm = TRUE),
            SD = sd(dsm_c, na.rm = TRUE),
            min = min(dsm_c, na.rm = TRUE),
            max = max(dsm_c, na.rm = TRUE)) |>
  mutate(var = "DSM-5 OUD Symptom Count",
        n = as.numeric(""),
        perc = as.numeric("")) |>
  select(var, n, perc, everything())

past_month_opioid <- intake |>
  select(var = whoassist_month_1_opioid) |>
  mutate(var = factor(var, levels = c("no", "yes"),
                      labels = c("No", "Yes"))) |> 
  group_by(var) |>
  summarise(n = n()) |>
  mutate(perc = (n / n_total) * 100) |>
  drop_na() |> 
  add_row(var = "Past Month Opioid Use", .before = 1)

past_month_detox <- intake |>
  select(var = other_tx_2) |>
  group_by(var) |>
  summarise(n = n()) |>
  mutate(perc = (n / n_total) * 100) |>
  drop_na() |> 
  add_row(var = "Past Month Detox or Residential Treatment", .before = 1)

past_month_psych <- intake |>
  select(var = other_tx_1) |>
  group_by(var) |>
  summarise(n = n()) |>
  mutate(perc = (n / n_total) * 100) |>
  drop_na() |> 
  add_row(var = "Past Month Psychiatric Medication", .before = 1)

opioid_preferred <- intake |>
  select(var = whoassist_opioid_3) |>
  mutate(var = factor(var,
                      levels = c("Fentanyl (Sublimaze, Actiq, apache, goodfella, TNT)",
                                 "Heroin (black tar, black pearl, black, china white, dope, white lady, smack, snow, speedball)",
                                 "Prescription opioid not for opioid treatment (OxyContin, Vicodin, Percocet, Opana)",
                                 "Medication for opioid treatment (e.g., Suboxone, Methadone, etc.)"),
                      labels = c("Fentanyl",
                                 "Heroin",
                                 "Prescription opioid not for opioid treatment",
                                 "Medication for opioid treatment"))) |> 
  group_by(var) |>
  summarise(n = n()) |>
  mutate(perc = (n / n_total) * 100) |>
  drop_na() |> 
  add_row(var = "Preferred Opioid", .before = 1)

roa_preferred <- intake |>
  select(var = whoassist_opioid_4) |>
  mutate(var = factor(var, 
                      levels = c("Injection (IV, muscle, under skin)",
                                 "Oral (swallow, chew)",
                                 "Smoke (chase)",
                                 "Sniff or snort",
                                 "Other"),
                      labels = c("Injection",
                                 "Oral",
                                 "Smoke",
                                 "Sniff or snort",
                                 "Other"))) |> 
  group_by(var) |>
  summarise(n = n()) |>
  mutate(perc = (n / n_total) * 100) |>
  drop_na() |> 
  add_row(var = "Preferred Route of Administration", .before = 1)

od <- intake |>
  select(var = whoassist_life_overdose) |>
  mutate(var = factor(var, 
                      levels = c("No",
                                 "1 time",
                                 "2-3 times",
                                 "4-5 times",
                                 "More than 5 times"),
                      labels = c("Never",
                                 "1 time",
                                 "2-3 times",
                                 "4-5 times",
                                 "More than 5 times"))) |> 
  group_by(var) |>
  summarise(n = n()) |>
  mutate(perc = (n / n_total) * 100) |>
  drop_na() |> 
  add_row(var = "Lifetime History of Overdose", .before = 1)

dsm <- intake |>
  select(var = dsm_c) |>
  mutate(var = case_match(var,
                          0 ~ "Under threshold (0-1)",
                          1 ~ "Under threshold (0-1)",
                          2 ~ "Mild (2-3)",
                          3 ~ "Mild (2-3)",
                          4 ~ "Moderate (4-5)",
                          5 ~ "Moderate (4-5)",
                          6 ~ "Severe (6+)",
                          7 ~ "Severe (6+)",
                          8 ~ "Severe (6+)",
                          9 ~ "Severe (6+)",
                          10 ~ "Severe (6+)",
                          11 ~"Severe (6+)"),
         var = factor(var, levels = c("Under threshold (0-1)",
                                      "Mild (2-3)",
                                      "Moderate (4-5)",
                                      "Severe (6+)"))) |> 
  group_by(var) |>
  summarise(n = n()) |>
  mutate(perc = (n / n_total) * 100) |>
  drop_na() |> 
  add_row(var = "Self-reported DSM-5 OUD Symptom Count", .before = 1) |> 
  add_row(tibble(var = "Mild (2-3)", n = 0, perc = 0), .before = 3)


table_dem <- dem_age |> 
  bind_rows(dem_gender) |> 
  bind_rows(dem_orientation) |> 
  bind_rows(dem_race) |> 
  bind_rows(dem_geography) |> 
  bind_rows(dem_education) |> 
  bind_rows(dem_employment) |> 
  bind_rows(dem_income) |> 
  bind_rows(dsm) |>
  bind_rows(past_month_opioid) |> 
  bind_rows(past_month_detox) |> 
  bind_rows(past_month_psych) |> 
  bind_rows(opioid_preferred) |> 
  bind_rows(roa_preferred) |> 
  bind_rows(od) |> 
  mutate(perc = round(perc, 1)) |> 
  rename(` ` = var,
         N = n,
         `%` = perc)
```


```{r}
table_ci <- read_csv(here::here(path_models_risk2, "contrast_ablate_v10.csv"),
                    show_col_types = FALSE) 
```


### Table 1: Demographics and Clinical Characteristics

```{r}
#| label: tbl-risk2dem
#| tbl-cap: "Demographic and Clinical Characteristics"

footnote_table_dem_a <- "N = 296"


table_dem |> 
  knitr::kable() |> 
  kable_classic() |> 
  kableExtra::group_rows(start_row = 2, end_row = 7) |> 
  kableExtra::group_rows(start_row = 9, end_row = 12) |> 
  kableExtra::group_rows(start_row = 14, end_row = 18) |> 
  kableExtra::group_rows(start_row = 20, end_row = 26) |> 
  kableExtra::group_rows(start_row = 28, end_row = 29) |> 
  kableExtra::group_rows(start_row = 31, end_row = 36) |> 
  kableExtra::group_rows(start_row = 38, end_row = 43) |> 
  kableExtra::group_rows(start_row = 45, end_row = 52) |> 
  kableExtra::group_rows(start_row = 54, end_row = 57) |> 
  kableExtra::group_rows(start_row = 59, end_row = 60) |> 
  kableExtra::group_rows(start_row = 62, end_row = 63) |> 
  kableExtra::group_rows(start_row = 65, end_row = 66) |> 
  kableExtra::group_rows(start_row = 68, end_row = 71) |>
  kableExtra::group_rows(start_row = 73, end_row = 77) |>
  kableExtra::group_rows(start_row = 79, end_row = 83) |>
  kableExtra::footnote(general = c(footnote_table_dem_a), escape=FALSE) 
```

### Table 2: Model Comparisons

```{r }
#| label: tbl-risk2model
#| tbl-cap: "Median difference in auROC, 95% Bayesian credible interval (CI), and posterior probability that that the auROC difference was larger than 0 for all ablated model contrasts."

footnote_table_model <- "Median auROC differences greater than 0 indicate the full model, on average, performed better than the ablated model (i.e., full vs. ablated daily survey, full vs. ablated geolocation, full vs. ablated daily survey and geolocation). Bayesian CI represents the range of values where there is a 95% probability that the true auROC difference lies within that range. Probability indicates the posterior probability that this difference is greater than 0 (i.e., the full model is performing better)."

table_ci |> 
  mutate(`Bayesian CI` = str_c("[", round(lower, 3), ", ", round(upper, 3), "]"),
         `Median auROC Difference` = as.character(round(median, 3)),
         Probability = sprintf("%.3f", probability)) |> 
  select(Contrast = contrast, `Median auROC Difference`, `Bayesian CI`, Probability) |> 
  knitr::kable() |> 
  kable_classic() |> 
  kableExtra::column_spec(1, width = "25em") |> 
  kableExtra::add_footnote(label = footnote_table_model,
                           notation = "none",
                           escape = FALSE) 
```


