---
title: "intro"
format: html
date: last-modified
bibliography: references.bib
---

# Introduction

## Substance Use Disorders

In 2023, over 46 million U.S. adults had a substance use disorder in the past year [@substanceabuseandmentalhealthservicesadministration2023NSDUHDetailed]. This is nearly 18% of the U.S. adult population.

Substance use disorders are associated with high rates of morbidity and mortality. Opioid overdose rates remain high and continue to increase each year [@IncreasesDrugOpioid; @friedmanTrendsDrugOverdose2022]. Excessive alcohol use is a leading preventable cause of death, with the majority of these deaths caused by alcohol-attributed cancer, heart problems and stroke, and liver cirrhosis [@ARDIAlcoholAttributableDeaths]. Additionally, alcohol-impaired driving accounts for over 30% of traffic fatalities each year [@unitedstatesdepartmentoftransportation2024].  

The economic cost of substance use disorders is substantial. In 2016 the economic cost associated with substance use disorders was estimated to exceed \$442 billion in lost productivity, health care expenses, law enforcement, and other criminal justice costs [@substanceabuseandmentalhealthservicesadministrationusFacingAddictionAmerica2016]. When also accounting for costs associated with loss of life and reduced quality of life, one research group estimated that in 2017 the cost of opioid use disorder alone exceeded \$1 trillion [@florenceEconomicBurdenOpioid2021]. 

## Treatment

Substance use disorders are chronic conditions, characterized by high relapse rates. [@mclellanDrugDependenceChronic2000; @dennisManagingAddictionChronic2007], substantial co-morbidity with other physical and mental health problems [@substanceabuseandmentalhealthservicesadministration2023NSDUHDetailed; @dennisManagingAddictionChronic2007], and an increased risk of mortality [@hedegaardDrugOverdoseDeaths; @centersfordiseasecontrolandpreventioncdcAnnualAverageUnited].  

Initial treatments, including medication (e.g., methadone, buprenorphine, and naltrexone for opioid use disorder and acamprosate, disulfiram, and naltrexone for alcohol use disorder) and evidenced-based psychosocial treatments (e.g., relapse prevention [@marlattRelapsePreventionMaintenance1985; @marlattRelapsePreventionSecond2007], mindfulness-based relapse prevention [@bowenMindfulnessBasedRelapsePrevention2021], and cognitive-behavioral therapy [@lieseCognitiveBehavioralTherapyAddictive2022]), are efficacious for symptom stabilization and harm reduction when provided. Unfortunately, too often individuals do not receive treatment [@substanceabuseandmentalhealthservicesadministration2023NSDUHDetailed]. 

Equally concerning, is the lack of continuing support and care provided to individuals after completing initial treatment [@stanojlovicTargetingBarriersSubstance2021; @sociasAdoptingCascadeCare2016]. Continuing care, including on-going monitoring, tailored adjustments to lifestyle and behaviors over time, and when necessary re-engagement with more intensive treatment, is the gold standard for treating chronic conditions, like diabetes, hypertension, and asthma. Similarly, substance use treatment has been shown to be most effective when care is prescribed over longer durations and involves active efforts to keep patients engaged in their recovery [@mckayImpactContinuingCare2021]. Yet, for reasons including cost and insurance reimbursement issues, lack of collaborative provider teams, passive referral processes, geographic barriers to accessing services, patient dropout, and changes in the patient’s clinical needs over time [@dennisManagingAddictionChronic2007; @taiTreatmentSubstanceUse2013; @mckayImpactContinuingCare2021; @stanojlovicTargetingBarriersSubstance2021], our current treatment system for substance use disorders does not not appear to have the capacity for long-term clinician-delivered care. This leaves individuals left to determine on their own "How can I best support my recovery today?"

This type of self-monitoring can be extremely difficult. The risk factors that precede lapse (i.e., single instances of goal-inconsistent substance use) and full relapse back to harmful use during recovery are individualized, numerous, dynamic and interactive [@witkiewitzModelingComplexityPosttreatment2007; @brandonRelapseRelapsePrevention2007]. Therefore, the optimal supports to address these risk factors and encourage continued, successful recovery vary both across individuals and within an individual over time. 

<!--could make the point then that although people arent receiving initial treatment, we  have them ready but for continuing care, we likely need to develop an entirely new system of care.-->

## Recovery Monitoring and Support System

An algorithm-guided recovery monitoring and support system could help patients monitor their current and future risk of lapse and make adjustments in their activities and supports to meet their recovery goals after initial treatment. Such a tool could offer personalized, adaptive recommendations aligned with evidenced-based care (i.e., relapse prevention model) and prompt individuals to engage with support at times of high risk. For example, individuals could receive daily messages about changes in their lapse risk and receive personalized recommendations based on top features contributing to their risk, like an urge surfing recommendation for someone with strong cravings. Moreover, it would provide a scalable option for long-term monitoring and support to address the substantial unmet need for continuing care for substance use disorders. 

<!--this makes it sound like there are only these two pre-reqs.  There are likely many - though maybe the ones I am thinking of can be rolled into these two large categories.   The system must be low burden, the system must be fair, the system must be trusted are the first three I think of!-->
For such a system to exist, two pre-requisites must be met. One, the system must be able to collect a rich and densely sampled source (or sources) of risk-relevant data. Two, the system must have access to a model that can predict substance use with high performance and temporal precision and have interpretable model inputs for support recommendations to be mapped onto. Advances in both smartphone sensing [@mohrPersonalSensingUnderstanding2017] and machine learning [@hastieElementsStatisticalLearning2009] now make this possible. Smartphone sensing approaches (e.g., ecological momentary assessment [EMA], geolocation sensing) can provide the frequent, longitudinal measurement of proximal risk factors that is necessary for prediction of future lapses with high temporal precision. <!--small point but this structure in this paragraph and the next are confusing.  You raise two pre-reqs.  Then you say we can do both.  They you have on setence about the first and then the next paragraph is about the second.  Parallel structures in writing are easier to follow.   Fine to have short paragraphs and end with sensing and machine learning make this posible. then two short paragraphs -one about sensing and one about ML-->

Machine learning models can handle the high dimensional feature sets that may result from feature engineering densely sampled raw EMA over time. They can also accommodate non-linear and interactive relationships between features and lapse probability.  And methods from interpretable machine learning can be used to understand which risk features contribute most strongly to a lapse prediction for a specific individual at a specific moment in time.

<!--OK, you do get to this but it feels too late and tacked on at the end.  Also not a strong ending before moving to aims.  Maybe this could be a footnote to the two pre-reqs (and that could be "At least two pre-req must be met" or something similar).  -->
Of course, these are not the only things needed for a successful recovery monitoring support system. For example, people must be willing and able to provide sensing data and the system must able to provide risk-relevant feedback to the individual in a useful and clinically helpful way. While important, these questions are outside the scope of the current proposal (see @wyantAcceptabilityPersonalSensing2023 and @wyantOptimizingMessageComponentsinprep).


## Aims of this proposal

This dissertation proposal <!--describes a program of research that seeks to develop...--> provides an initial line of research for developing an algorithm to be used in a recovery monitoring support system. Two projects (chapters 2 and 3) are completed and two projects (chapters 3 and 4) are <!--planned and under development--> proposed future directions. These projects are explained more below:

**Chapter 2:** Machine learning models for temporally precise lapse prediction in alcohol use disorder 

This project demonstrated that 4x daily EMA could be used to build temporally precise machine learning models to predict alcohol lapses. Specifically, we built three models to predict the probability of an alcohol lapse in the next hour, day, and week. These models that predict immediate lapses can be used to provide personalized support recommendations to address immediate risks for possible lapses. Models can be updated each day <!--why each day when you just told me your have an hour model-->to provide individuals information about changes in their risk and make supportive recommendations based on the top features contributing to their risk. <!--the recommendations part of this project really wasnt its focus and the validity of these recommendations werent tested.  Seems the focus for this paper was mostly on performance at varying levels of temporal precision.-->For example, recommending a coping with craving activity when someone has increased craving. Importantly, this assumes that the recommendations can be implemented immediately and that the individual has already learned the skill.   

<!--but i see you are bringing in the rec idea to make clear this gap.  Maybe this chapter could have a first paragraph about performance and temporal precision.  The second paragraph could talk about using SHAPs from these models to make recommendations about immediate support.   I would them move the gap (advanced warning) to the section on chap 3-->    
However, many appropriate support recommendations take time to set up, and are not available in the moment (e.g., attending a self-help meeting, planning an outing with important people in their life, or scheduling an appointment with a therapist). In these cases, patients would benefit from advanced warning about changes in their risk. This advanced warning could be obtained by lagging lapse probability predictions further into the future (e.g., predicting lapse probability in a 24-hour window that begins two weeks in the future). 


**Chapter 3:**  Lagged predictions of next day alcohol use for personalized and adaptive continuing care support
    
This project showed that the same 4x daily EMA could be used to predict alcohol use occurring within a 24-hour window up to two weeks into the future. We considered several meaningful lags for prediction windows: 1 day, 3 days, 1 week, and 2 weeks. These models with lagged prediction windows can also be used to provide personalized support recommendations, but with the added benefit of advanced warning. Thus, giving an individual extra time to implement the recommendation.

<!--OK, it works better here to talk about limitations in the same section with the study.   Maybe that will work in the second chapter too if the paragraphs are structured a bit better.   I wonder if we the first study/chapter 2 also focused us on using probabilites to guide rather than predicting lapses because of the low PPV.  We reported PPV, correct?-->
The models were promising, however, limitations exist. Most notably was a lack of fairness <!--  this suggest that fairness might be worked in as a third pre-req that you will address in your program of research-->in the performance of our models between demographic subgroups. Our models performed better for individuals who were <!--Non-Hispanic-->White, male, and had a personal income above the Federal poverty line. 
    
Additionally, as participants only provided data for up to three months, we were limited by how far into the future we could predict. It is likely true that even more advanced warning (e.g., 1 month) would be helpful for implementing more intensive supports (e.g., re-engagement with clinician-care).


**Chapter 4:** Using sensing data to predict opioid use <!--use or lapse??-->in a national sample of patients with opioid use disorder
    
In this project, I will take advantage of an existing dataset of personal sensing data (i.e., 1X daily EMA, geolocation) and opioid lapse reports from a national sample of people with opioid use disorder. This project will allow us to generalize lapse prediction algorithms to other drugs beyond alcohol. Notably, a successful model will demonstrate that lapse prediction can be done with a drug where its use is illegal. <!--what is illegal important??  May not be obvious to your reader--> <!--Also, keep structure parallel.  If you decide to keep study limitations with the chapter that has the limitation rather than acknowledging it with the study that addresses it (as you did above), you will want to note at the end of chap 3 that studies from both 2-3 focused on alcohol lapses.  Not clear that this will work for lapses with drugs that may be even more stigmatized and/or illegal, where willingness to report use and even risk factors may be lower.  But then, think if you are really going to address this by just switching drugs.  How do we know people were willing to report?  Yes, they report some use but maybe some people dont or most people dont report many of their lapses?   Is high performance sufficient to say this works?  Maybe yes?-->
    
This project will also address the noted limitations of the previous studies. First, these data offer more diversity with regard to race/ethnicity, income, and geographic location. <!--this will allow us to determine if improving the quality of the training data withh respect to diversity is sufficient to address issues of fairness-->We expect a more representative dataset will help mitigate some of the fairness discrepancies seen in our race/ethnicity and income subgroup comparisons.

<!--I didnt really think this through before but now see that you plan to develop traditional lagged models as well as  immediate lapse?  That seems like a lot of work.  An alternative might be to acknowledge at this point (as a limitation at the end of this section), that having to develop many lagged models for many different lags into the future is time consuming, cumbersome and still only provides coarse understanding of time-course.  Lets move to a time-series approach for lags!-->
Second, participants provided data for up to 12 months. This extended window of recovery (12 months vs. 3 months) is critical for evaluating the value of an algorithm intended for ongoing continuing care support. The longer duration of participation will also give us the chance to experiment with lagged prediction windows further than two weeks into the future (i.e., no lag, 2-week, and 4-week lag).

<!--you havent mentioned the use of EMA only as a limitation prior to this.  Should you?  Seems that would keep the structure the same-->
Third, in this proposed project, model features will be derived from two complementary sensing methods: 1X daily EMA and continuous geolocation data. Geolocation is a passive sensing method that could compliment EMA well. It could provide insight into information difficult to measure with self-report (e.g., the amount of time spent in risky locations, or changes in routine that could indicate life stressors) or that would add additional burden by increasing the number of questions on the EMA. Furthermore, by adding more data sources gives us more features and that could mean better personalization of predictions and recommendations for more people.

An inherent limitation of a traditional machine learning approach is that it does not capture the repeated nature of sensing data. Each lapse prediction is treated as a new independent observation. We can account for the repeated observations by grouping participants during resampling (i.e., all of a participant's data is either in the training set or test tet)<!--this first part addresses a different issue and is not really central here to your point.  Focus only on this second half of sentence--> and engineering features that capture individual changes over time to produce unbiased and precise estimates of predictive performance. However, these models do not allow for causal inference <!--careful on causal inference.  Many would say none of these approachhes will establish cause without manipulation.  I'd focus on better understanding the temporal dynamics of lapse risk over longer periods which is important clinically and maybe also to address explanatory questions about timecourse of risks, and clusters of individuals on different trajectories-->about or understanding of how lapse risk evolves over time. 

<!--again, need to decide where limitations go and keep all of it together.-->    
Additionally, different models must be built to predict lapses at varying times in the future. For example, a recovery monitoring support system that detects both immediate lapse risk (i.e., in the next 24 hours) and future lapse risk (i.e, in the next 2 weeks and in the next month) would need three models. This can quickly become computationally expensive and inefficient. 


**Chapter 5:** State-space models for idiographic risk monitoring and recovery support recommendations

In this project, we propose Hierarchical Bayesian state-space models as an alternative approach for prediction models. State-space models model measured inputs (e.g., ema responses, time spent in risky locations, time spent at home) and outputs (i.e., lapse or no lapse) from time series data with latent states. 
    
The hierarchical nature, will allow us to better use and understand time-varying information. A single model can be used to predict a lapse at any point in the future, eliminating the need for multiple models for predicting immediate and future lapse risk. State-space models also explicitly model how the latent state of an individual's lapse risk evolves over time. These states can then be extracted from the model and used for understanding lapse risk and improving recovery support recommendations. 
  
Given the heterogeneity in lapse risk and the complex interactions between environment and individual differences, an idiographic <!--this idea abouut idiographic vs. nomethetic can just be dropped in without explanation or definionts!  Not sure you need these terms here either.  You could focus on future predictionns withh same model, and then say better modeling of time series within participantions along with an approach that learns parameter estiamtes (dont use that term) for each person might be expected to perform better too.  Maybe not needed for immediate predictions where we already do well but perhaps important for lagged predictions where we dont do as well.-->approach to lapse prediction may be better suited for tailoring recovery support recommendations. Therefore, we will build an individual model for each participant using their own data. We will attach group-level Bayesian priors generated from the remaining participants <!--too much detail for here-->to help prevent over-fitting and improve stability of the models' performance. Idiographic models also may help mitigate issues of unfairness<!--good-->, as the model will weigh the individual's own data more heavily than the group level priors.
  
Therefore, we will evaluate the performance and fairness of a state-space model approach for opioid lapse risk prediction using the EMA and geolocaion dataset introduced in Chapter 4. We will also assess the usability of latent states as intervenable targets for recommendations.
    
